import {emptyState,validate,ordered,total,comparison,project,validDate} from './assets-model.js';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),yen=n=>n===null||n===undefined?'—':'¥'+Math.round(n).toLocaleString('ja-JP'),name=a=>a.institution+(a.owner?' / '+a.owner+'口座':''),today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
let state=emptyState(),ready=false,busy=false,selected='',cloud,editBase,selectedSim=new Set(),simInitialized=false;
const demo=['localhost','127.0.0.1'].includes(location.hostname)&&new URLSearchParams(location.search).has('demo');
function status(message,error=false){$('status').textContent=message;$('status').className=error?'error':'muted';}
function delta(n){return n===null?'<span class="muted">比較なし</span>':`<span class="delta ${n>0?'up':n<0?'down':'flat'}">${n>0?'↑ +':n<0?'↓ −':'→ '}${yen(Math.abs(n))}</span>`;}
function chart(target,points,color='#244fe0'){
  if(!points.length||points.every(p=>p.value===null)){$(target).innerHTML='<div class="empty">記録すると、ここに推移が表示されます。</div>';return;}
  const w=760,h=260,left=85,right=20,top=20,bottom=42,max=Math.max(1,...points.map(p=>p.value||0))*1.08,x=i=>left+(w-left-right)*(points.length===1?.5:i/(points.length-1)),y=v=>h-bottom-v/max*(h-top-bottom),fmt=n=>Math.abs(n)>=1e12?(n/1e12).toPrecision(3)+'兆':Math.abs(n)>=1e8?(n/1e8).toFixed(1)+'億':Math.round(n/10000).toLocaleString()+'万';
  let segments=[],segment=[];points.forEach((p,i)=>{if(p.value===null){if(segment.length)segments.push(segment);segment=[];}else segment.push(`${x(i)},${y(p.value)}`)});if(segment.length)segments.push(segment);
  const labelStep=Math.max(1,Math.ceil(points.length/6));
  $(target).innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(points.map(p=>p.label+' '+yen(p.value)).join('、'))}">${[0,.5,1].map(f=>`<line x1="${left}" x2="${w-right}" y1="${y(max*f)}" y2="${y(max*f)}" stroke="#e6ecf5"/><text x="${left-12}" y="${y(max*f)+5}" text-anchor="end" font-size="14" fill="#69768a">${fmt(max*f)}</text>`).join('')}${segments.map(s=>`<polyline points="${s.join(' ')}" fill="none" stroke="${color}" stroke-width="3"/>`).join('')}${points.map((p,i)=>`${p.value===null?'':`<circle cx="${x(i)}" cy="${y(p.value)}" r="4" fill="${color}"><title>${esc(p.label)} ${yen(p.value)}</title></circle>`}${i%labelStep===0||i===points.length-1?`<text x="${x(i)}" y="${h-13}" text-anchor="middle" font-size="14" fill="#69768a">${esc(p.label)}</text>`:''}`).join('')}</svg>`;
}
function render(){
  $('add').disabled=!ready;$('manage').disabled=!ready;$('export').disabled=!ready;$('restore').disabled=!ready;
  const records=ordered(state);if(!records.some(r=>r.date===selected))selected=records.at(-1)?.date||'';
  $('dateSelect').innerHTML=records.length?records.toReversed().map(r=>`<option value="${r.date}">${r.date}</option>`).join(''):'<option value="">記録なし</option>';$('dateSelect').value=selected;$('edit').disabled=!selected||!ready;
  const c=comparison(state,selected||today(),$('compare').value),current=c.current;
  $('total').textContent=yen(total(current));$('asof').textContent=current?current.date+' 時点の記録':'まずは今の残高を記録しましょう。';$('count').textContent=current?Object.keys(current.balances).length+'口座を記録':'残高未入力';
  $('deltaLabel').textContent=($('compare').value==='month'?'前月':'前回')+'からの増減';$('delta').innerHTML=c.delta===null?'—':delta(c.delta);$('compareNote').textContent=c.previous?c.previous.date+'との比較'+(c.complete?'':'（共通の'+c.matched+'口座のみ）'):'比較する記録がありません';$('movement').innerHTML=current?`<span class="up">${c.rows.filter(r=>r.delta>0).length}</span> / <span class="down">${c.rows.filter(r=>r.delta<0).length}</span>`:'—';
  const chartId=$('chartAccount').value;$('chartAccount').innerHTML='<option value="">資産全体</option>'+state.accounts.map(a=>`<option value="${esc(a.id)}">${esc(name(a))}</option>`).join('');$('chartAccount').value=state.accounts.some(a=>a.id===chartId)?chartId:'';renderTrend();
  const key=$('sort').value,field=key==='percent'?'percent':key==='value'?'value':'delta',direction=key==='loss'?1:-1;
  const rows=[...c.rows].sort((a,b)=>a[field]===null?1:b[field]===null?-1:direction*(a[field]-b[field]));let rank=0,last=null;
  $('ranking').innerHTML=rows.map((r,i)=>{if(r[field]!==null){if(last!==r[field])rank=i+1;last=r[field];}return `<tr><td>${r[field]===null?'—':`<span class="rank">${rank}</span>`}</td><td><b>${esc(r.institution)}</b><br><span class="muted">${esc(r.owner?r.owner+'口座':'')}${r.archived?' · 非表示':''}</span></td><td>${yen(r.value)}</td><td>${delta(r.delta)}</td><td class="${r.percent>0?'up':r.percent<0?'down':'flat'}">${r.percent===null?'—':(r.percent>0?'+':'')+r.percent.toFixed(1)+'%'}</td></tr>`;}).join('')||'<tr><td colspan="5">「残高を記録」から最初の金額を入力してください。</td></tr>';
  $('rankingNote').textContent=c.previous?`${selected} と ${c.previous.date} の比較。比較できない口座は順位の対象外です。`:'比較する記録がないため、増減の順位はまだ表示されません。';
  $('history').innerHTML=records.toReversed().map(r=>`<tr><td>${r.date}</td><td>${yen(total(r))}</td><td>${Object.keys(r.balances).length}</td><td><button data-edit="${r.date}">編集</button></td></tr>`).join('')||'<tr><td colspan="4">まだ記録がありません。</td></tr>';
  $('history').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openRecord(b.dataset.edit));renderSimulationAccounts();
}
function renderTrend(){
  const records=ordered(state),id=$('chartAccount').value,months=new Map();for(const r of records)months.set(r.date.slice(0,7),r);
  const points=[];if(records.length){const d=new Date(records[0].date.slice(0,7)+'-01T00:00:00Z'),end=records.at(-1).date.slice(0,7);while(d.toISOString().slice(0,7)<=end){const m=d.toISOString().slice(0,7),r=months.get(m);points.push({label:m,value:r?(id?r.balances[id]??null:total(r)):null});d.setUTCMonth(d.getUTCMonth()+1);}}
  chart('trend',points);
}
function renderSimulationAccounts(){const r=ordered(state).at(-1);const accounts=state.accounts.filter(a=>r&&Object.hasOwn(r.balances,a.id));if(!simInitialized&&accounts.length){selectedSim=new Set(accounts.filter(a=>a.institution.includes('証券')).map(a=>a.id));simInitialized=true;}
  $('simDate').textContent=r?'最新の記録（'+r.date+'）をもとに試算':'残高を記録すると試算できます。';$('simAccounts').innerHTML=accounts.map(a=>`<label class="checkrow"><input type="checkbox" data-sim="${a.id}" ${selectedSim.has(a.id)?'checked':''}><span>${esc(name(a))}</span><span>${yen(r.balances[a.id])}</span></label>`).join('');$('simAccounts').querySelectorAll('input').forEach(el=>el.onchange=()=>{el.checked?selectedSim.add(el.dataset.sim):selectedSim.delete(el.dataset.sim);renderSimulation()});renderSimulation();}
function renderSimulation(){try{const r=ordered(state).at(-1),p=r?Object.entries(r.balances).reduce((n,[id,v])=>n+(selectedSim.has(id)?v:0),0):0,rest=(total(r)||0)-p;if(!$('rate').value||!$('years').value)throw Error('年利と運用期間を入力してください');const rate=Number($('rate').value),years=Number($('years').value),values=project(p,rate,years),end=values.at(-1).value;$('simError').textContent='';$('futureLabel').textContent=years+'年後の資産全体';$('future').textContent=r?yen(end+rest):'—';$('simSummary').textContent=r?`運用対象 ${yen(p)} → ${yen(end)}（${rate}%／年）。対象外 ${yen(rest)} は一定として計算。`:'先に残高を記録してください。';chart('projection',r?values.map(v=>({label:v.year+'年',value:v.value+rest})):[]);$('projectionRows').innerHTML=r?values.map(v=>`<tr><td>${v.year}年後</td><td>${yen(v.value)}</td><td>${yen(v.value+rest)}</td></tr>`).join(''):'';}catch(e){$('simError').textContent=e.message;$('future').textContent='—';$('projection').innerHTML='';$('projectionRows').innerHTML='';$('simSummary').textContent='';}}
function openModal(title,body){editBase=structuredClone(state);$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modalError').textContent='';if(!$('modal').open)$('modal').showModal();}
async function commit(next){if(!ready||busy)throw Error('読み込み・保存の完了をお待ちください');busy=true;$('close').disabled=true;$('modal').querySelectorAll('button').forEach(b=>b.disabled=true);status('保存しています…');try{validate(next);if(demo){next.revision++;state=next;render();}else await cloud.save(next,next.revision);status(demo?'サンプルを更新しました（保存なし）':'クラウドに保存しました');$('modal').close();}catch(e){$('modalError').textContent=e.message;status('保存できませんでした。入力内容は画面に残っています。',true);throw e;}finally{busy=false;$('close').disabled=false;$('modal').querySelectorAll('button').forEach(b=>b.disabled=false);}}
function openRecord(date){if(!ready)return;const existing=state.records.find(r=>r.date===date);const accounts=state.accounts.filter(a=>!a.archived||existing&&Object.hasOwn(existing.balances,a.id));openModal(existing?'残高を編集':'残高を記録',`<form id="recordForm"><label>記録日<input id="recordDate" type="date" min="2000-01-01" max="${today()}" value="${date||today()}" required ${existing?'readonly':''}></label><p class="muted">すべて円で入力。証券は口座全体の評価額、ビットコインは保有分の円換算額です。残高がない口座は0を入力してください。</p><button type="button" id="copyPrevious" class="quiet">前回の残高をコピー</button><div class="formrows">${accounts.map(a=>`<div class="inputrow"><label for="balance-${a.id}">${esc(a.institution)}<br><span class="muted">${esc(a.owner?a.owner+'口座':'円換算額')}</span></label><input id="balance-${a.id}" data-balance="${a.id}" aria-label="${esc(name(a))}の残高" inputmode="numeric" type="text" pattern="[0-9０-９,， ]+" value="${existing?.balances[a.id]??''}" required placeholder="0"></div>`).join('')}</div><p class="muted" id="inputTotal"></p><div class="actions"><button class="primary" type="submit">${existing?'変更を保存':'残高を保存'}</button></div></form>`);
  const inputs=[...$('modalBody').querySelectorAll('[data-balance]')],parse=v=>{const n=v.replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-65248)).replace(/[,，\s]/g,'');return /^\d+$/.test(n)?Number(n):NaN;},sumInputs=()=>{$('inputTotal').textContent='入力合計 '+yen(inputs.reduce((n,e)=>n+(Number.isFinite(parse(e.value))?parse(e.value):0),0));};inputs.forEach(e=>e.oninput=sumInputs);sumInputs();
  $('copyPrevious').onclick=()=>{const prev=ordered(editBase).filter(r=>r.date<$('recordDate').value).at(-1);if(!prev){$('modalError').textContent='これより前の記録がありません';return;}inputs.forEach(e=>e.value=prev.balances[e.dataset.balance]??'');sumInputs();$('modalError').textContent='前回の金額をコピーしました。現在の残高を確認して保存してください。';};
  $('recordForm').onsubmit=async e=>{e.preventDefault();try{const d=$('recordDate').value;if(!validDate(d)||d>today())throw Error('今日以前の記録日を入力してください');if(!existing&&editBase.records.some(r=>r.date===d))throw Error('この日の記録があります。「この記録を編集」から変更してください');const next=structuredClone(editBase),balances=Object.fromEntries(inputs.map(i=>[i.dataset.balance,parse(i.value)]));next.records=next.records.filter(r=>r.date!==d);next.records.push({date:d,balances});validate(next);selected=d;await commit(next);}catch(err){$('modalError').textContent=err.message;}};
}
function manage(){if(!ready)return;openModal('口座を管理',`<p class="muted">削除すると次回から入力欄に表示されなくなります。過去の残高は残り、いつでも戻せます。完全に手放した口座は、残高0円を記録してから削除してください。</p><button id="newAccount" class="primary">＋ 口座を追加</button><div>${state.accounts.map(a=>`<div class="accountrow"><div><b>${esc(a.institution)}</b><div class="muted">${esc(a.owner?a.owner+'口座':'')}${a.archived?' · 削除済み':''}</div></div><div class="actions"><button data-account="${a.id}">変更</button><button class="${a.archived?'':'danger'}" data-archive="${a.id}">${a.archived?'元に戻す':'削除'}</button></div></div>`).join('')}</div>`);$('newAccount').onclick=()=>editAccount();$('modalBody').querySelectorAll('[data-account]').forEach(b=>b.onclick=()=>editAccount(b.dataset.account));$('modalBody').querySelectorAll('[data-archive]').forEach(b=>b.onclick=async()=>{const next=structuredClone(editBase),a=next.accounts.find(a=>a.id===b.dataset.archive);a.archived=!a.archived;try{await commit(next);}catch{}});}
function editAccount(id){const a=state.accounts.find(a=>a.id===id);openModal(a?'口座名を変更':'口座を追加',`<form id="accountForm" class="formrows"><label>金融機関・項目名<input id="institution" maxlength="60" required value="${esc(a?.institution||'')}" placeholder="例：楽天証券"></label><label>名義・口座名<input id="owner" maxlength="40" value="${esc(a?.owner||'')}" placeholder="例：大輔"></label><p class="muted">名称の変更は過去の表示にも反映されます。</p><button class="primary">保存</button></form>`);$('accountForm').onsubmit=async e=>{e.preventDefault();const next=structuredClone(editBase),item={id:id||crypto.randomUUID(),institution:$('institution').value.trim(),owner:$('owner').value.trim(),archived:a?.archived||false};if(id)next.accounts[next.accounts.findIndex(a=>a.id===id)]=item;else next.accounts.push(item);try{await commit(next);}catch(e){$('modalError').textContent=e.message;}};}
$('close').onclick=()=>{if(!busy)$('modal').close()};$('modal').addEventListener('cancel',e=>{if(busy)e.preventDefault()});$('add').onclick=()=>openRecord();$('edit').onclick=()=>openRecord(selected);$('manage').onclick=manage;$('dateSelect').onchange=()=>{selected=$('dateSelect').value;render()};$('compare').onchange=render;$('sort').onchange=render;$('chartAccount').onchange=renderTrend;$('rate').oninput=renderSimulation;$('years').oninput=renderSimulation;
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('overview').hidden=b.dataset.tab!=='overview';$('simulation').hidden=b.dataset.tab!=='simulation';};
$('export').onclick=()=>{if(!ready)return;const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='assets-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('restore').onclick=()=>{if(ready)$('restoreFile').click()};$('restoreFile').onchange=async()=>{try{const f=$('restoreFile').files[0];if(!f)return;if(f.size>750000)throw Error('ファイルが大きすぎます');const incoming=validate(JSON.parse(await f.text()));openModal('バックアップから復元',`<p>${incoming.accounts.length}口座・${incoming.records.length}件の記録で、現在の資産管理データを置き換えます。</p><p>現在の記録を残したい場合は、先にバックアップを書き出してください。</p><button id="confirmRestore" class="primary">この内容で復元</button>`);$('confirmRestore').onclick=async()=>{try{await commit({...incoming,revision:editBase.revision});}catch{}};}catch(e){status(e.message,true);}finally{$('restoreFile').value='';}};
if(demo){state.records=['2026-06-30','2026-07-31','2026-08-31','2026-09-28'].map((date,m)=>({date,balances:Object.fromEntries(state.accounts.map((a,i)=>[a.id,Math.round((i<3?2600000:i<7?1100000:600000)*(1+m*(i===7?-.04:.035)))]))}));ready=true;$('auth').hidden=true;$('app').hidden=false;$('demoNote').hidden=false;$('identity').textContent='サンプル表示';render();status('サンプルデータを表示中');}
else{try{cloud=await import('./assets-cloud.js');$('login').onclick=async()=>{try{await cloud.login()}catch(e){$('authStatus').textContent='ログインできませんでした。ポップアップの許可を確認してください。'}};$('logout').onclick=async()=>{try{await cloud.logout()}catch(e){status(e.message,true)}};cloud.watch(u=>{ready=false;state=emptyState();selected='';simInitialized=false;selectedSim.clear();$('modal').close();$('auth').hidden=!!u;$('app').hidden=!u;$('logout').hidden=!u;$('authStatus').textContent='家計簿と同じアカウントでログインしてください。';$('identity').textContent=u?.email||'';render();status('クラウドから読み込んでいます…');},s=>{state=s;ready=true;render();status('クラウドと同期済み');},e=>{ready=false;render();status('データを読み込めませんでした。再読み込みしてください。'+(e.code==='permission-denied'?' 保存先へのアクセスが許可されていません。':''),true);});}catch(e){$('authStatus').textContent='接続できませんでした。通信環境を確認して再読み込みしてください。';}}
