import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import {getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import {getFirestore,doc,runTransaction,onSnapshot} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
import {key,categories,validateState,markDuplicates} from './ledger.js';
import {parseFile} from './importer.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
let user=null,unsubscribe=null,onUpdate=()=>{},onUser=()=>{};
const previews=new Map();
export const login=()=>signInWithPopup(auth,new GoogleAuthProvider());
export const logout=()=>signOut(auth);
export function watch(update,changed){onUpdate=update;onUser=changed;onAuthStateChanged(auth,u=>{user=u;previews.clear();unsubscribe?.();onUser(u);if(u)unsubscribe=onSnapshot(doc(db,'users',u.uid,'household','meta'),()=>onUpdate(),e=>onUser(u,e));});}
async function transaction(action){if(!user)throw Error('Googleアカウントでログインしてください');const uid=user.uid;return runTransaction(db,async tx=>{const metaRef=doc(db,'users',uid,'household','meta');const snap=await tx.get(metaRef);const meta=snap.exists()?snap.data():{months:[],rules:[],revision:0};const monthDocs=new Map();for(const m of meta.months){const ref=doc(db,'users',uid,'months',m);const s=await tx.get(ref);monthDocs.set(m,{ref,value:s.exists()?s.data():{entries:[],complete:false,imports:[]}});}const before=JSON.stringify(meta);const originals=new Map([...monthDocs].map(([m,v])=>[m,JSON.stringify(v.value)]));const state={entries:[...monthDocs.values()].flatMap(x=>x.value.entries),rules:meta.rules||[],months:[...monthDocs].map(([month,x])=>({month,complete:x.value.complete})),imports:[...monthDocs.values()].flatMap(x=>x.value.imports||[]),changes:[]};const result=await action(state,meta,monthDocs);if(user?.uid!==uid)throw Error('ログイン状態が変わりました');let dirty=JSON.stringify(meta)!==before;for(const [m,v]of monthDocs){if(JSON.stringify(v.value)!==originals.get(m)){if(new TextEncoder().encode(JSON.stringify(v.value)).length>750000)throw Error('この月のデータ容量が上限を超えています。保存は行っていません。');tx.set(v.ref,v.value);dirty=true;}}if(dirty){meta.months=[...monthDocs.keys()].sort();meta.revision=(meta.revision||0)+1;tx.set(metaRef,meta);}return result;});}
function monthRecord(month,months){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw Error('対象月を選択してください');if(!months.has(month))months.set(month,{ref:doc(db,'users',user.uid,'months',month),value:{entries:[],complete:false,imports:[]}});return months.get(month).value;}
export async function api(path,body){
if(path==='state'||path==='export')return transaction(s=>s);
if(path==='import-preview'){if(!body.files?.length||body.files.length>8)throw Error('ファイルは1〜8個までです');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(body.month))throw Error('対象月を選んでください');const groups=[];for(const f of body.files)groups.push(await parseFile(f,body.personMap));if(groups.reduce((n,g)=>n+g.rows.length,0)>5000)throw Error('一度に5000明細以内で取り込んでください');const s=await api('state');const token=crypto.randomUUID();previews.set(token,{uid:user.uid,month:body.month,groups});return {token,month:body.month,rows:markDuplicates(groups.map(g=>g.rows),s),files:groups.map(g=>({filename:g.filename,period:g.period})),warnings:groups.flatMap(g=>g.warnings)};}
if(path==='restore'){const incoming=validateState(body);return transaction((s,meta,months)=>{if(s.entries.length)throw Error('初回移行は明細が空のときだけ行えます');for(const r of incoming.entries)monthRecord(r.month,months).entries.push(r);for(const [month,record]of months){record.value.complete=!!incoming.months?.find(m=>m.month===month)?.complete;record.value.imports=(incoming.imports||[]).filter(i=>i.month===month);}meta.rules=incoming.rules;return {added:incoming.entries.length};});}
const result=await transaction((s,meta,months)=>{
if(path==='month-status'){monthRecord(body.month,months).complete=body.complete===true;return {};}
if(path==='change'){if(!categories.includes(body.category))throw Error('カテゴリが無効です');const entry=s.entries.find(r=>r.id===body.id);if(!entry||entry.kind!=='支出')throw Error('明細が見つかりません');const name=key(entry.name),oldRule=meta.rules.find(r=>r.name===name),token=crypto.randomUUID();meta.undo={token,id:entry.id,month:entry.month,name,before:entry.category,rule:oldRule?.category??null,after:body.category,revision:(meta.revision||0)+1,state:'saved'};entry.category=body.category;meta.rules=meta.rules.filter(r=>r.name!==name);meta.rules.push({name,category:body.category});return {token};}
if(path==='only'||path==='undo'){const h=meta.undo;if(!h||h.token!==body.token||h.revision!==meta.revision||!(path==='only'?['saved']:['saved','only']).includes(h.state))throw Error('別の変更があるため、明細のカテゴリを選び直してください');if(h.state==='saved'){meta.rules=meta.rules.filter(r=>r.name!==h.name);if(h.rule!==null)meta.rules.push({name:h.name,category:h.rule});}if(path==='undo'){const entry=s.entries.find(r=>r.id===h.id);if(!entry)throw Error('明細が見つかりません');entry.category=h.before;}h.state=path==='only'?'only':'undone';h.revision=meta.revision+1;return {};}
if(path==='import-commit'){const p=previews.get(body.token);if(!p||p.uid!==user.uid)throw Error('ファイルを選び直してください');const fresh=markDuplicates(p.groups.map(g=>g.rows),s).filter(r=>!r.duplicate);if(fresh.length){const m=monthRecord(p.month,months);for(const original of fresh){const {duplicate,...r}=original;m.entries.push({...r,id:'import-'+crypto.randomUUID(),month:p.month});}m.complete=body.complete===true;m.imports.push(...p.groups.map(g=>({id:crypto.randomUUID(),month:p.month,filename:g.filename,period:g.period,created:new Date().toISOString()})));}return {added:fresh.length,month:p.month};}
throw Error('対応していない操作です');});if(path==='import-commit')previews.delete(body.token);return result;
}
