export const categories=['固定費','食費','日用品','衣服・ファッション','美容・ケア','医療・健康','子ども用品','水道・光熱費','通信費','サブスク','趣味・娯楽','旅行・宿泊','交通費','その他','未分類'];
export const normalize=v=>String(v??'').normalize('NFKC').trim().replace(/\s+/g,' ');
export const key=v=>normalize(v).toLowerCase();
export function fingerprint(r){let n=key(r.name);if(r.source==='楽天'&&n.includes('etc'))n='etc';if(r.source==='楽天'&&n.includes('投信積立'))n='楽天証券投信積立';return JSON.stringify([r.source,r.date,n,r.amount,r.person]);}
export function validateState(s){if(!Array.isArray(s.entries)||!Array.isArray(s.rules))throw Error('家計簿のバックアップではありません');const ids=new Set();for(const r of s.entries){if(!/^[\w-]{1,100}$/.test(r.id)||ids.has(r.id)||!/^\d{4}-(0[1-9]|1[0-2])$/.test(r.month)||!/^\d{4}\/\d{2}\/\d{2}$/.test(r.date)||typeof r.name!=='string'||r.name.length>1000||!Number.isSafeInteger(r.amount)||!['本人','家族'].includes(r.person)||!['楽天','AMEX','手入力'].includes(r.source)||!['支出','投資','チャージ','カード返済'].includes(r.kind)||!(categories.includes(r.category)||r.category==='対象外'))throw Error('明細データの形式を確認してください');ids.add(r.id);}for(const r of s.rules)if(typeof r.name!=='string'||!categories.includes(r.category))throw Error('分類ルールの形式を確認してください');validateRecurring(s.recurring||[]);return s;}
export function classify(name,amount){if(name.includes('前回分口座振替'))return ['カード返済','対象外'];if(name.includes('投信積立'))return ['投資','対象外'];if((name.includes('楽天ペイ')||name.includes('au PAY'))&&name.includes('チャージ'))return ['チャージ','対象外'];if(amount<0)return ['支出','未分類'];const rules=[['食費',['FCD','クイックペイ','WAON','マクドナルド','まいばすけっと','ロイヤルホスト','イトーヨーカドー 食品','イオンフード','UBER EATS','スターバックス','セブンイレブン','COFFEE CAMP','鈴木水産','グランツリー 専門店 食品','業務スーパー','食品館あおば']],['サブスク',['LiME','Netflix','U-NEXT','OPENAI','Apple iTunes']],['交通費',['Suica','イデミツ','ETC']],['水道・光熱費',['ミツウロコ','水道料金']],['通信費',['ソフトバンク','ドコモ']],['衣服・ファッション',['ユニクロ','ZOZOTOWN']],['美容・ケア',['湘南美容']],['医療・健康',['病院','クリニック']],['子ども用品',['西松屋']],['趣味・娯楽',['ぴあファンクラブ']],['旅行・宿泊',['ふふ箱根']],['日用品',['ウエルシア','マツモトキヨシ','サンドラッグ']]];for(const [c,terms] of rules)if(terms.some(t=>key(name).includes(key(t))))return ['支出',c];return ['支出',/[都道府県].+[市区町村]/.test(name)?'その他':'未分類'];}
export function markDuplicates(groups,state){const existing=new Map(),seen=new Map();for(const r of state.entries){const fp=fingerprint(r);existing.set(fp,(existing.get(fp)||0)+1);}const rules=new Map(state.rules.map(r=>[r.name,r.category]));return groups.flatMap(group=>{const local=new Map();const rows=group.map(original=>{const r={...original};const fp=fingerprint(r),n=(local.get(fp)||0)+1;local.set(fp,n);r.duplicate=n<=Math.max(existing.get(fp)||0,seen.get(fp)||0);if(r.kind==='支出'&&rules.has(key(r.name)))r.category=rules.get(key(r.name));return r;});for(const [fp,n]of local)seen.set(fp,Math.max(seen.get(fp)||0,n));return rows;});}

export const currentMonth=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit'}).format(new Date());
export function validateRecurring(list){if(!Array.isArray(list)||list.length>200)throw Error('固定費は200件以内で登録してください');const ids=new Set();for(const item of list){if(!/^[\w-]{1,100}$/.test(item.id)||ids.has(item.id)||!Array.isArray(item.versions)||!item.versions.length)throw Error('固定費の形式を確認してください');ids.add(item.id);const months=new Set();for(const v of item.versions){if(!/^20\d{2}-(0[1-9]|1[0-2])$/.test(v.fromMonth)||months.has(v.fromMonth)||typeof v.name!=='string'||!v.name.trim()||v.name.length>200||!Number.isSafeInteger(v.amount)||v.amount<=0||!['本人','家族'].includes(v.person)||!Number.isInteger(v.day)||v.day<1||v.day>31||typeof v.active!=='boolean')throw Error('固定費の名称・金額・適用月・引落日を確認してください');months.add(v.fromMonth);}}return list;}
export function withRecurring(state,now=currentMonth()){const entries=state.entries.filter(r=>!r.deleted),recurring=state.recurring||[];const months=new Set([now,...state.months.map(m=>m.month),...entries.map(r=>r.month)]);const end=[...months].sort().at(-1);for(const item of recurring){const versions=[...item.versions].sort((a,b)=>a.fromMonth.localeCompare(b.fromMonth));for(let month=versions[0].fromMonth;month<=end;){const v=versions.filter(v=>v.fromMonth<=month).at(-1);if(v?.active){const [y,m]=month.split('-').map(Number),day=Math.min(v.day,new Date(y,m,0).getDate());entries.push({id:'fixed-'+item.id+'-'+month,recurringId:item.id,month,date:month.replace('-','/')+'/'+String(day).padStart(2,'0'),name:v.name,amount:v.amount,category:'固定費',kind:'支出',source:'固定費',person:v.person});months.add(month);}const [y,m]=month.split('-').map(Number);month=m===12?(y+1)+'-01':y+'-'+String(m+1).padStart(2,'0');}}return {...state,entries,months:[...months].sort().map(month=>({month,complete:state.months.find(m=>m.month===month)?.complete||false}))};}
